# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Infinitum
name: Tony Yu
intro: When, where and why.
email: mar29th@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal blog. Usually I talk about musings in software development and
  technology. Sometimes it can just be a personal post about daily matters.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mar29th.github.io" # the base hostname & protocol for your site
github_username: mar29th

# Build settings
markdown: kramdown
